name: workflow1

on:
 push:
  branches:
  - main
  - dev
 schedule:
  - cron: '*/5 * * * *'
 workflow_dispatch:
jobs:
 job1:
  runs-on: ubuntu-latest

  steps:
   - name: task 1 for printing OS details
     run: uname -a
   - name: task2 to print hostname
     run: hostname
