name: notification
on:
  push:
    branches:
      - main

jobs:
    build:
     runs-on: ubuntu-latest
     steps:
       - name: step first
         run: |
           echo "test step 1"
           sleep 10
       - name: step2
         run: echo "step 2 run"
       - name: step3
         run: echo "step 3 run"

    build2:
     runs-on: ubuntu-latest
     steps:
       - name: step1
         run: |
           echo "test step 1"
           sleep 10    

    full_test:
     runs-on: ubuntu-latest
     needs: [ build, build2 ]
     if: ${{ always () }}
     steps:
       - name: step1
         run: |
           echo "test step 1"
           sleep 10    
    deploy:
     runs-on: ubuntu-latest
     steps:
       - name: step1
         run: |
           echo "test step 1"
           sleep 10
     needs: full_test

    notification:
     runs-on: ubuntu-latest
     needs: build
     if: ${{ needs.build.result == 'failure' || failure() }}
     steps:
       - name: notify
         run: |
           echo "Build step got failed"
           sleep 10
